config/routes.rb
    get({ "#{root_path}/:username/preferences" => "users#preferences", constraints: { username: USERNAME_ROUTE_FORMAT } }.merge(index == 1 ? { as: :email_preferences } : {}))
    get "#{root_path}/:username/preferences/email" => "users_email#index", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/account" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/profile" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/emails" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/notifications" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/categories" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/tags" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/interface" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/apps" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
    put "#{root_path}/:username/preferences/email" => "users_email#update", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/about-me" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/badge_title" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
    put "#{root_path}/:username/preferences/badge_title" => "users#badge_title", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/username" => "users#preferences", constraints: {username: USERNAME_ROUTE_FORMAT}
    put "#{root_path}/:username/preferences/username" => "users#username", constraints: {username: USERNAME_ROUTE_FORMAT}
    delete "#{root_path}/:username/preferences/user_image" => "users#destroy_user_image", constraints: {username: USERNAME_ROUTE_FORMAT}
    put "#{root_path}/:username/preferences/avatar/pick" => "users#pick_avatar", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/preferences/card-badge" => "users#card_badge", constraints: {username: USERNAME_ROUTE_FORMAT}
    put "#{root_path}/:username/preferences/card-badge" => "users#update_card_badge", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/staff-info" => "users#staff_info", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/summary" => "users#summary", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/invited" => "users#invited", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/invited_count" => "users#invited_count", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/invited/:filter" => "users#invited", constraints: {username: USERNAME_ROUTE_FORMAT}
    post "#{root_path}/action/send_activation_email" => "users#send_activation_email"
    get "#{root_path}/:username/summary" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/activity/topics.rss" => "list#user_topics_feed", format: :rss, constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/activity.rss" => "posts#user_posts_feed", format: :rss, constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/activity" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/activity/:filter" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/badges" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/notifications" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/notifications/:filter" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/activity/pending" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
    delete "#{root_path}/:username" => "users#destroy", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/by-external/:external_id" => "users#show", constraints: {external_id: /[^\/]+/}
    get "#{root_path}/:username/flagged-posts" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/deleted-posts" => "users#show", constraints: {username: USERNAME_ROUTE_FORMAT}
    get "#{root_path}/:username/topic-tracking-state" => "users#topic_tracking_state", constraints: {username: USERNAME_ROUTE_FORMAT}
  end

  get "user-badges/:username.json" => "user_badges#username", constraints: {username: USERNAME_ROUTE_FORMAT}, defaults: {format: :json}
  get "user-badges/:username" => "user_badges#username", constraints: {username: USERNAME_ROUTE_FORMAT}

  post "user_avatar/:username/refresh_gravatar" => "user_avatars#refresh_gravatar", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "letter_avatar/:username/:size/:version.png" => "user_avatars#show_letter", format: false, constraints: { hostname: /[\w\.-]+/, size: /\d+/, username: USERNAME_ROUTE_FORMAT}
  get "user_avatar/:hostname/:username/:size/:version.png" => "user_avatars#show", format: false, constraints: { hostname: /[\w\.-]+/, size: /\d+/, username: USERNAME_ROUTE_FORMAT }

  # in most production settings this is bypassed
  get "letter_avatar_proxy/:version/letter/:letter/:color/:size.png" => "user_avatars#show_proxy_letter"

  get "highlight-js/:hostname/:version.js" => "highlight_js#show", format: false, constraints: { hostname: /[\w\.-]+/ }

  get "stylesheets/:name.css.map" => "stylesheets#show_source_map", constraints: { name: /[-a-z0-9_]+/ }
  get "stylesheets/:name.css" => "stylesheets#show", constraints: { name: /[-a-z0-9_]+/ }

  post "uploads" => "uploads#create"

  # used to download original images
  get "uploads/:site/:sha(.:extension)" => "uploads#show", constraints: { site: /\w+/, sha: /\h{40}/, extension: /[a-z0-9\.]+/i }
  # used to download attachments
  get "uploads/:site/original/:tree:sha(.:extension)" => "uploads#show", constraints: { site: /\w+/, tree: /([a-z0-9]+\/)+/i, sha: /\h{40}/, extension: /[a-z0-9\.]+/i }
  # used to download attachments (old route)
  get "uploads/:site/:id/:sha" => "uploads#show", constraints: { site: /\w+/, id: /\d+/, sha: /\h{16}/ }

  get "posts" => "posts#latest", id: "latest_posts"
  get "private-posts" => "posts#latest", id: "private_posts"
  get "posts/by_number/:topic_id/:post_number" => "posts#by_number"
  get "posts/:id/reply-history" => "posts#reply_history"
  get "posts/:username/deleted" => "posts#deleted_posts", constraints: {username: USERNAME_ROUTE_FORMAT}
  get "posts/:username/flagged" => "posts#flagged_posts", constraints: {username: USERNAME_ROUTE_FORMAT}

  resources :groups, id: USERNAME_ROUTE_FORMAT do
    get "posts.rss" => "groups#posts_feed", format: :rss
    get "mentions.rss" => "groups#mentions_feed", format: :rss

    get 'activity' => "groups#show"
    get 'activity/:filter' => "groups#show"
    get 'members'
    get 'posts'
    get 'topics'
    get 'mentions'
    get 'messages'
    get 'counts'
    get 'mentionable'
    get 'logs' => 'groups#histories'

    member do
      put "members" => "groups#add_members"
      delete "members" => "groups#remove_member"
      post "request_membership" => "groups#request_membership"
      post "notifications" => "groups#set_notifications"
    end
  end

  # aliases so old API code works
  delete "admin/groups/:id/members" => "groups#remove_member", constraints: AdminConstraint.new
  put "admin/groups/:id/members" => "groups#add_members", constraints: AdminConstraint.new

  resources :posts do
    put "bookmark"
    put "wiki"
    put "post_type"
    put "rebake"
    put "unhide"
    get "replies"
    get "revisions/latest" => "posts#latest_revision"
    get "revisions/:revision" => "posts#revisions", constraints: { revision: /\d+/ }
    put "revisions/:revision/hide" => "posts#hide_revision", constraints: { revision: /\d+/ }
    put "revisions/:revision/show" => "posts#show_revision", constraints: { revision: /\d+/ }
    put "revisions/:revision/revert" => "posts#revert", constraints: { revision: /\d+/ }
    put "recover"
    collection do
      delete "destroy_many"
      put "merge_posts"
    end
  end

  get 'notifications' => 'notifications#index'
  put 'notifications/mark-read' => 'notifications#mark_read'
  # creating an alias cause the api was extended to mark a single notification
  # this allows us to cleanly target it
  put 'notifications/read' => 'notifications#mark_read'

  match "/auth/:provider/callback", to: "users/omniauth_callbacks#complete", via: [:get, :post]
  match "/auth/failure", to: "users/omniauth_callbacks#failure", via: [:get, :post]

  resources :clicks do
    collection do
      get "track"
    end
  end

  get "excerpt" => "excerpt#show"

  resources :post_action_users
  resources :post_actions do
    collection do
      get "users"
      post "defer_flags"
    end
  end
  resources :user_actions

  resources :badges, only: [:index]
  get "/badges/:id(/:slug)" => "badges#show"
  resources :user_badges, only: [:index, :create, :destroy]


  get '/c', to: redirect('/categories')

  resources :categories, :except => :show
  post "category/:category_id/move" => "categories#move"
  post "categories/reorder" => "categories#reorder"
  post "category/:category_id/notifications" => "categories#set_notifications"
  put "category/:category_id/slug" => "categories#update_slug"

  get "categories_and_latest" => "categories#categories_and_latest"

  get "c/:id/show" => "categories#show"
  get "c/:category_slug/find_by_slug" => "categories#find_by_slug"

app/helpers/topics_helper.rb
module TopicsHelper
  include ApplicationHelper

  def render_topic_title(topic)
    link_to(gsub_emoji_to_unicode(topic.title),topic.relative_url)
  end

  def categories_breadcrumb(topic)
    breadcrumb = []

    category = topic.category
    if category && !category.uncategorized?
      if (parent = category.parent_category)
        breadcrumb.push url: parent.url, name: parent.name
      end
      breadcrumb.push url: category.url, name: category.name
    end

    Plugin::Filter.apply(:topic_categories_breadcrumb, topic, breadcrumb)
  end

end

app/views/topics/plain.html.erb
<!DOCTYPE html>
<html lang="<%=SiteSetting.default_locale%>">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title><%= @topic_view.topic.title %></title>
  <%= raw crawlable_meta_data(title: @topic_view.title, description: @topic_view.summary, image: @topic_view.image_url, read_time: @topic_view.read_time, like_count: @topic_view.like_count) %>
  <% if @topic_view.prev_page %>
    <link rel="prev" href="<%= @topic_view.prev_page_path -%>">
  <% end %>
  <% if @topic_view.next_page %>
    <link rel="next" href="<%= @topic_view.next_page_path -%>">
  <% end %>
</head>
<body>
<% @topic_view.posts.each do |post| %>
  <% if post.user %>
    <div class='creator'>
      <b><%= post.user.username %></b> <%= "(#{post.user.name})" if (SiteSetting.display_name_on_posts && SiteSetting.enable_names?) %> at <%= post.created_at.to_formatted_s(:long_ordinal) %> — #<%= post.post_number %>
    </div>
    <div class='post'>
      <% if post.hidden %>
        <%= t('flagging.user_must_edit').html_safe %>
      <% else %>
        <%= post.cooked.html_safe %>
      <% end %>
    </div>
    <hr/>
  <% end %>
<% end %>
<p>
  <% if @topic_view.prev_page %>
    <%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev' %>
  <% end %>
  <% if @topic_view.next_page %>
    <b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next' %></b>
  <% end %>
</p>
</body>

app/views/topics/show.html.erb
<h1>
  <%= render_topic_title(@topic_view.topic) %>
</h1>

<% @breadcrumbs = categories_breadcrumb(@topic_view.topic)
    if @breadcrumbs.present? %>
<div id='breadcrumbs'>
  <% @breadcrumbs.each_with_index do |c,i| %>
    <div id="breadcrumb-<%=i%>" itemscope itemtype="http://data-vocabulary.org/Breadcrumb"
      <%-if (i+1) < @breadcrumbs.length%>
        itemref="breadcrumb-<%=(i+1)%>"
      <%-end%>>
      <a href="<%=c[:url]%>" itemprop="url">
        <span itemprop="title"><%=c[:name]%></span>
      </a>
    </div>
  <% end %>
</div>
<% end %>

<% if SiteSetting.tagging_enabled %>
  <% @tags = @topic_view.topic.tags %>
  <% if @tags.present? %>
    <div class='tags-list' itemscope itemtype='http://schema.org/ItemList'>
      <% @tags.each do |tag| %>
        <div itemprop='itemListElement' itemscope itemtype='http://schema.org/ListItem'>
          <meta itemprop='url' content='<%= "#{Discourse.base_url}/tags/#{tag.name}" %>'>
          <a href='<%= "#{Discourse.base_url}/tags/#{tag.name}" %>' itemprop='item'>
            <span itemprop='name'><%= tag.name -%></span>
          </a>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>


<%= server_plugin_outlet "topic_header" %>

<hr>

<%- if include_crawler_content? %>

<% @topic_view.posts.each do |post| %>
  <div itemscope itemtype='http://schema.org/DiscussionForumPosting'>
    <% if (u = post.user) %>
      <div class='creator'>
        <span>
          <a href='<%= Discourse.base_uri %>/u/<%= u.username %>'><b itemprop='author'><%= u.username %></b></a>
           <%= "(#{u.name})" if (SiteSetting.display_name_on_posts && SiteSetting.enable_names? && !u.name.blank?) %>
           <time datetime='<%= post.created_at.to_formatted_s(:iso8601) %>' itemprop='datePublished'>
             <%= post.created_at %>
           </time>
        </span>
        <span itemprop='position'>#<%= post.post_number %></span>
      </div>
      <div class='post' itemprop='articleBody'>
        <%= post.hidden ? t('flagging.user_must_edit').html_safe : post.cooked.html_safe %>
      </div>
      <meta itemprop='interactionCount' content='UserLikes:<%= post.like_count %>'>
      <meta itemprop='interactionCount' content='UserComments:<%= post.reply_count %>'>
      <meta itemprop='headline' content='<%= @topic_view.title %>'>
      <hr>
      <% if @topic_view.link_counts[post.id] && @topic_view.link_counts[post.id].length > 0 %>
        <% @topic_view.link_counts[post.id].each do |link| %>
          <% if link[:reflection] && link[:title].present? %>
            <a href="<%=link[:url]%>"><%=link[:title]%></a>
            <hr>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

<% if @topic_view.prev_page || @topic_view.next_page %>
  <div role='navigation' itemscope itemtype='http://schema.org/SiteNavigationElement'>
    <% if @topic_view.prev_page %>
      <span itemprop='url'><%= link_to t(:prev_page), @topic_view.prev_page_path, rel: 'prev', itemprop: 'name' %></span>
    <% end %>
    <% if @topic_view.next_page %>
      <span itemprop='url'><b><%= link_to t(:next_page), @topic_view.next_page_path, rel: 'next', itemprop: 'name' %></b></span>
    <% end %>
  </div>
<% end %>

<% end %>

<% content_for :head do %>
  <%= auto_discovery_link_tag(@topic_view, {action: :feed, slug: @topic_view.topic.slug, topic_id: @topic_view.topic.id}, title: t('rss_posts_in_topic', topic: @topic_view.title), type: 'application/rss+xml') %>
  <%= raw crawlable_meta_data(title: @topic_view.title, description: @topic_view.summary, image: @topic_view.image_url, read_time: @topic_view.read_time, like_count: @topic_view.like_count) %>

  <% if @topic_view.prev_page || @topic_view.next_page %>
    <% if @topic_view.prev_page %>
      <link rel="prev" href="<%= @topic_view.prev_page_path -%>">
    <% end %>
    <% if @topic_view.next_page %>
      <link rel="next" href="<%= @topic_view.next_page_path -%>">
    <% end %>
  <% end %>
<% end %>

<% content_for(:title) { @title || "#{gsub_emoji_to_unicode(@topic_view.page_title)} - #{SiteSetting.title}" } %>

<% if @topic_view.print %>
  <% content_for :after_body do %>
      <style media="print">
        /* For readability */
        a, a:visited {
          color: #0088cc !important;
        }
      </style>
      <script>
        document.addEventListener("DOMContentLoaded", function() {
          window.print();
        });
      </script>
  <% end %>
<% end %>

app/views/topics/show.rss.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <% topic_url = @topic_view.absolute_url %>
    <% lang = SiteSetting.find_by_name('default_locale').try(:value) %>
    <% site_email = SiteSetting.find_by_name('contact_email').try(:value) %>
    <title><%= @topic_view.title %></title>
    <link><%= topic_url %></link>
    <description><%= @topic_view.posts.first.raw %></description>
    <% if lang %><language><%= lang.sub('_', '-')%></language><% end %>
    <lastBuildDate><%= @topic_view.topic.bumped_at.rfc2822 %></lastBuildDate>
    <category><%= @topic_view.topic.category.name %></category>
    <atom:link href="<%= topic_url %>.rss" rel="self" type="application/rss+xml" />
    <% @topic_view.recent_posts.each do |post| %>
      <% next unless post.user %>
      <item>
        <title><%= @topic_view.title %></title>
        <dc:creator><![CDATA[<%= "@#{post.user.username}#{" #{post.user.name}" if (post.user.name.present? && SiteSetting.enable_names?)}" -%>]]></dc:creator>
        <description><![CDATA[
          <% post_url = Discourse.base_url + post.url %>
          <p><%= t('author_wrote', author: link_to("@#{post.user.username}", user_url(post.user.username_lower))).html_safe %></p>
          <blockquote>
            <% if post.hidden %>
              <%= t('flagging.user_must_edit').html_safe %>
            <% else %>
              <%= post.cooked.html_safe %>
            <% end %>
          </blockquote>
          <p><%= link_to t('read_full_topic'), post_url %></p>
        ]]></description>
        <link><%= post_url %></link>
        <pubDate><%= post.created_at.rfc2822 %></pubDate>
        <guid isPermaLink="false"><%= Discourse.current_hostname %>-post-<%= post.topic_id %>-<%= post.post_number %></guid>
        <source url="<%= @topic_view.absolute_url %>.rss"><%= @topic_view.title %></source>
      </item>
    <% end %>
  </channel>
</rss>