config/routes.rb
require "sidekiq/web"
require_dependency "scheduler/web"
require_dependency "admin_constraint"
require_dependency "staff_constraint"
require_dependency "homepage_constraint"
require_dependency "permalink_constraint"

# This used to be User#username_format, but that causes a preload of the User object
# and makes Guard not work properly.
USERNAME_ROUTE_FORMAT = /[\w.\-]+?/ unless defined? USERNAME_ROUTE_FORMAT

BACKUP_ROUTE_FORMAT = /.+\.(sql\.gz|tar\.gz|tgz)/i unless defined? BACKUP_ROUTE_FORMAT

Discourse::Application.routes.draw do

  match "/404", to: "exceptions#not_found", via: [:get, :post]
  get "/404-body" => "exceptions#not_found_body"

  post "webhooks/mailgun"  => "webhooks#mailgun"
  post "webhooks/sendgrid" => "webhooks#sendgrid"
  post "webhooks/mailjet"  => "webhooks#mailjet"
  post "webhooks/mandrill" => "webhooks#mandrill"
  post "webhooks/sparkpost" => "webhooks#sparkpost"

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"
    mount Logster::Web => "/logs"
  else
    # only allow sidekiq in master site
    mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new(require_master: true)
    mount Logster::Web => "/logs", constraints: AdminConstraint.new
  end

  resources :about do
    collection do
      get "live_post_counts"
    end
  end

  get "finish-installation" => "finish_installation#index"
  get "finish-installation/register" => "finish_installation#register"
  post "finish-installation/register" => "finish_installation#register"
  get "finish-installation/confirm-email" => "finish_installation#confirm_email"
  put "finish-installation/resend-email" => "finish_installation#resend_email"

  resources :directory_items

  get "site" => "site#site"
  namespace :site do
    get "settings"
    get "custom_html"
    get "banner"
    get "emoji"
  end

  get "site/basic-info" => 'site#basic_info'
  get "site/statistics" => 'site#statistics'

  get "srv/status" => "forums#status"

  get "wizard" => "wizard#index"
  get "wizard/qunit" => "wizard#qunit"
  get 'wizard/steps' => 'steps#index'
  get 'wizard/steps/:id' => "wizard#index"
  put 'wizard/steps/:id' => "steps#update"

  namespace :admin, constraints: StaffConstraint.new do
    get "" => "admin#index"

    get 'plugins' => 'plugins#index'

    resources :site_settings, constraints: AdminConstraint.new do
      collection do
        get "category/:id" => "site_settings#index"
      end
    end

    get "reports/:type" => "reports#show"

    resources :groups, constraints: AdminConstraint.new do
      collection do
        post "refresh_automatic_groups" => "groups#refresh_automatic_groups"
        get 'bulk'
        get 'bulk-complete' => 'groups#bulk'
        put 'bulk' => 'groups#bulk_perform'
      end
      member do
        put "owners" => "groups#add_owners"
        delete "owners" => "groups#remove_owner"
      end
    end

    get "groups/:type" => "groups#show", constraints: AdminConstraint.new
    get "groups/:type/:id" => "groups#show", constraints: AdminConstraint.new

    resources :users, id: USERNAME_ROUTE_FORMAT, except: [:show] do
      collection do
        get "list" => "users#index"
        get "list/:query" => "users#index"
        get "ip-info" => "users#ip_info"
        delete "delete-others-with-same-ip" => "users#delete_other_accounts_with_same_ip"
        get "total-others-with-same-ip" => "users#total_other_accounts_with_same_ip"
        put "approve-bulk" => "users#approve_bulk"
        delete "reject-bulk" => "users#reject_bulk"
      end
      put "suspend"
      put "delete_all_posts"
      put "unsuspend"
      put "revoke_admin", constraints: AdminConstraint.new
      put "grant_admin", constraints: AdminConstraint.new
      post "generate_api_key", constraints: AdminConstraint.new
      delete "revoke_api_key", constraints: AdminConstraint.new
      put "revoke_moderation", constraints: AdminConstraint.new
      put "grant_moderation", constraints: AdminConstraint.new
      put "approve"
      post "refresh_browsers", constraints: AdminConstraint.new
      post "log_out", constraints: AdminConstraint.new
      put "activate"
      put "deactivate"
      put "block"
      put "unblock"
      put "trust_level"
      put "trust_level_lock"
      put "primary_group"
      post "groups" => "users#add_group", constraints: AdminConstraint.new
      delete "groups/:group_id" => "users#remove_group", constraints: AdminConstraint.new
      get "badges"
      get "leader_requirements" => "users#tl3_requirements"
      get "tl3_requirements"
      put "anonymize"
      post "reset_bounce_score"
    end
    get "users/:id.json" => 'users#show', defaults: {format: 'json'}
    get 'users/:id/:username' => 'users#show', constraints: {username: USERNAME_ROUTE_FORMAT}
    get 'users/:id/:username/badges' => 'users#show'
    get 'users/:id/:username/tl3_requirements' => 'users#show'


    post "users/sync_sso" => "users#sync_sso", constraints: AdminConstraint.new
    post "users/invite_admin" => "users#invite_admin", constraints: AdminConstraint.new

    resources :impersonate, constraints: AdminConstraint.new

    resources :email, constraints: AdminConstraint.new do
      collection do
        post "test"
        get "sent"
        get "skipped"
        get "bounced"
        get "received"
        get "rejected"
        get "/incoming/:id/raw" => "email#raw_email"
        get "/incoming/:id" => "email#incoming"
        get "/incoming_from_bounced/:id" => "email#incoming_from_bounced"
        get "preview-digest" => "email#preview_digest"
        get "send-digest" => "email#send_digest"
        get "smtp_should_reject"
        post "handle_mail"
      end
    end

    scope "/logs" do
      resources :staff_action_logs,     only: [:index]
      get 'staff_action_logs/:id/diff' => 'staff_action_logs#diff'
      resources :screened_emails,       only: [:index, :destroy]
      resources :screened_ip_addresses, only: [:index, :create, :update, :destroy] do
        collection do
          post "roll_up"
        end
      end
      resources :screened_urls,         only: [:index]
    end

    get "/logs" => "staff_action_logs#index"

    get "customize" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/themes" => "themes#index", constraints: AdminConstraint.new
    get "customize/colors" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/colors/:id" => "color_schemes#index", constraints: AdminConstraint.new
    get "customize/permalinks" => "permalinks#index", constraints: AdminConstraint.new
    get "customize/embedding" => "embedding#show", constraints: AdminConstraint.new
    put "customize/embedding" => "embedding#update", constraints: AdminConstraint.new

    get "flags" => "flags#index"
    get "flags/:filter" => "flags#index"
    post "flags/agree/:id" => "flags#agree"
    post "flags/disagree/:id" => "flags#disagree"
    post "flags/defer/:id" => "flags#defer"

    resources :themes, constraints: AdminConstraint.new
    post "themes/import" => "themes#import"
    post "themes/upload_asset" => "themes#upload_asset"
    get "themes/:id/preview" => "themes#preview"

    scope "/customize", constraints: AdminConstraint.new do
      resources :user_fields, constraints: AdminConstraint.new
      resources :emojis, constraints: AdminConstraint.new

      get 'themes/:id/:target/:field_name/edit' => 'themes#index'
      get 'themes/:id' => 'themes#index'

      # They have periods in their URLs often:
      get 'site_texts'          => 'site_texts#index'
      get 'site_texts/(:id)'    => 'site_texts#show',   constraints: { id: /[\w.\-\+]+/i }
      put 'site_texts/(:id)'    => 'site_texts#update', constraints: { id: /[\w.\-\+]+/i }
      delete 'site_texts/(:id)' => 'site_texts#revert', constraints: { id: /[\w.\-\+]+/i }

      get 'email_templates'          => 'email_templates#index'
      get 'email_templates/(:id)'    => 'email_templates#show',   constraints: { id: /[0-9a-z_.]+/ }
      put 'email_templates/(:id)'    => 'email_templates#update', constraints: { id: /[0-9a-z_.]+/ }
      delete 'email_templates/(:id)' => 'email_templates#revert', constraints: { id: /[0-9a-z_.]+/ }
    end

    resources :embeddable_hosts, constraints: AdminConstraint.new
    resources :color_schemes, constraints: AdminConstraint.new

    resources :permalinks, constraints: AdminConstraint.new

    get "version_check" => "versions#show"

    resources :dashboard, only: [:index] do
      collection do
        get "problems"
      end
    end

    resources :api, only: [:index], constraints: AdminConstraint.new do
      collection do
        get "keys" => "api#index"
        post "key" => "api#create_master_key"
        put "key" => "api#regenerate_key"
        delete "key" => "api#revoke_key"

        resources :web_hooks
        get 'web_hook_events/:id' => 'web_hooks#list_events', as: :web_hook_events
        get 'web_hooks/:id/events' => 'web_hooks#list_events'
        get 'web_hooks/:id/events/bulk' => 'web_hooks#bulk_events'
        post 'web_hooks/:web_hook_id/events/:event_id/redeliver' => 'web_hooks#redeliver_event'
        post 'web_hooks/:id/ping' => 'web_hooks#ping'
      end
    end

    resources :backups, only: [:index, :create], constraints: AdminConstraint.new do
      member do
        get "" => "backups#show", constraints: { id: BACKUP_ROUTE_FORMAT }
        put "" => "backups#email", constraints: { id: BACKUP_ROUTE_FORMAT }
        delete "" => "backups#destroy", constraints: { id: BACKUP_ROUTE_FORMAT }
        post "restore" => "backups#restore", constraints: { id: BACKUP_ROUTE_FORMAT }
      end
      collection do
        get "logs" => "backups#logs"
        get "status" => "backups#status"
        delete "cancel" => "backups#cancel"
        post "rollback" => "backups#rollback"
        put "readonly" => "backups#readonly"
        get "upload" => "backups#check_backup_chunk"
        post "upload" => "backups#upload_backup_chunk"
      end

app/controllers/finish_installation_controller.rb
class FinishInstallationController < ApplicationController
  skip_before_filter :check_xhr, :preload_json, :redirect_to_login_if_required
  layout 'finish_installation'

  before_filter :ensure_no_admins, except: ['confirm_email', 'resend_email']

  def index
  end

  def register
    @allowed_emails = find_allowed_emails

    @user = User.new
    if request.post?
      email = params[:email].strip
      raise Discourse::InvalidParameters.new unless @allowed_emails.include?(email)

      return redirect_confirm(email) if User.where(email: email).exists?

      @user.email = email
      @user.username = params[:username]
      @user.password = params[:password]
      @user.password_required!

      if @user.save
        @email_token = @user.email_tokens.unconfirmed.active.first
        Jobs.enqueue(:critical_user_email, type: :signup, user_id: @user.id, email_token: @email_token.token)
        return redirect_confirm(@user.email)
      end

    end
  end

  def confirm_email
    @email = session[:registered_email]
  end

  def resend_email
    @email = session[:registered_email]
    @user = User.where(email: @email).first
    if @user.present?
      @email_token = @user.email_tokens.unconfirmed.active.first
      if @email_token.present?
        Jobs.enqueue(:critical_user_email, type: :signup, user_id: @user.id, email_token: @email_token.token)
      end
    end
  end

  protected

    def redirect_confirm(email)
      session[:registered_email] = email
      redirect_to(finish_installation_confirm_email_path)
    end

    def find_allowed_emails
      return [] unless GlobalSetting.respond_to?(:developer_emails) && GlobalSetting.developer_emails.present?
      GlobalSetting.developer_emails.split(",").map(&:strip)
    end

    def ensure_no_admins
      preload_anonymous_data
      raise Discourse::InvalidAccess.new unless SiteSetting.has_login_hint?
    end
end

app/views/finish_installation/confirm_email.html.erb
<h1><%= t 'finish_installation.confirm_email.title' %></h1>

<%= raw(t 'finish_installation.confirm_email.message', email: @email) %>

<div class='row'>
  <%= button_to(finish_installation_resend_email_path, method: :put, class: 'wizard-btn') do %>
    <%= t 'finish_installation.resend_email.title' %>
  <% end %>
</div>

app/views/finish_installation/index.html.erb
<h1><%= t 'finish_installation.congratulations' %></h1>

<div class='row'>
  <%= image_tag "/images/wizard/tada.svg", class: "tada" %>
</div>

<div class='row help-text'>
  <%= t 'finish_installation.register.help' %>
</div>

<div class='row'>
  <%= link_to(finish_installation_register_path, class: 'wizard-btn primary') do %>
    <i class='fa fa-user'></i>
    <%= t 'finish_installation.register.button' %>
  <% end %>
</div>

app/views/finish_installation/register.html.erb
<h1><%= t 'finish_installation.register.title' %></h1>

<%- if @allowed_emails.present? %>
  <%= form_tag(finish_installation_register_path) do %>

    <div class='wizard-field text-field'>
      <label for="email">
        <span class="label-value"><%= t 'js.user.email.title' %></span>
      </label>

      <div class='input-area'>
        <%= select_tag :email, options_for_select(@allowed_emails, selected: params[:email]), class: 'combobox' %>
      </div>
    </div>

    <div class='wizard-field text-field <% if @user.errors[:username].present? %>invalid<% end %>'>
      <label for="username">
        <span class="label-value"><%= t 'js.user.username.title' %></span>
      </label>

      <div class='field-description'><%= t 'js.user.username.instructions' %></div>

      <div class='input-area'>
        <%= text_field_tag(:username, params[:username]) %>
      </div>
      <%- @user.errors[:username].each do |e| %>
        <div class='field-error-description'><%= e.to_s %></div>
      <%- end %>
    </div>

    <div class='wizard-field text-field <% if @user.errors[:username].present? %>invalid<% end %>'>
      <label for="password">
        <span class="label-value"><%= t 'js.user.password.title' %></span>
      </label>

      <div class='field-description'><%= t 'js.user.password.instructions', count: SiteSetting.min_admin_password_length  %></div>

      <div class='input-area'>
        <%= password_field_tag(:password, params[:password]) %>
      </div>
      <% @user.errors[:password].each do |e| %>
        <div class='field-error-description'><%= e.to_s %></div>
      <% end %>
    </div>

    <%= submit_tag(t('finish_installation.register.button'), class: 'wizard-btn primary') %>

  <%- end %>
<%- else -%>
  <p><%= raw(t 'finish_installation.register.no_emails') %></p>
<%- end %>

<script>
  (function() {
    $('select').select2({ width: '400px' });
  })();
</script>

app/views/finish_installation/resend_email.html.erb
<h1><%= t 'finish_installation.resend_email.title' %></h1>

<%= raw(t 'finish_installation.resend_email.message', email: @email) %>